# Generated by Django 4.1.2 on 2022-10-31 15:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="v2rayprofile",
            name="admin_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="v2rayprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="v2rayprofile",
            name="system_message",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="v2rayprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
