# Generated by Django 4.1.3 on 2022-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_v2rayprofile_v2ray_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="v2rayprofile",
            name="system_message",
        ),
        migrations.AlterField(
            model_name="v2rayprofile",
            name="v2ray_state",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="v2rayprofile",
            name="v2ray_state_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
