# Generated by Django 4.1.3 on 2022-11-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_remove_subscription_start_volume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ("-id",)},
        ),
    ]
