# Generated by Django 4.1.3 on 2022-11-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_alter_subscription_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="start_date",
            new_name="created_at",
        ),
    ]
