# Generated by Django 4.1.3 on 2022-12-09 11:47

from django.db import migrations


def _fill(apps, _):
    # from Users.models import V2RayProfile
    users_model = apps.get_model("Users", "V2RayProfile")
    for u_ in users_model.objects.all():
        for s_ in u_.subscription_set.filter(
            state="2", expired_at__isnull=True
        ):
            next_ = u_.subscription_set.filter(
                id__gt=s_.id, started_at__isnull=False
            )
            if next_.exists():
                s_.expired_at = next_.last().started_at
            else:
                s_.expired_at = u_.v2ray_state_date
            s_.save()


def _fill_rev(apps, _):
    subs_model = apps.get_model("Users", "Subscription")
    subs_model.objects.update(expired_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0009_subscription_expired_at"),
    ]

    operations = [
        migrations.RunPython(_fill, reverse_code=_fill_rev, atomic=True)
    ]
