# Generated by Django 4.1.5 on 2023-01-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0012_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="usage_at_expire",
        ),
        migrations.AddField(
            model_name="subscription",
            name="downlink",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="uplink",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
