# Generated by Django 4.1.5 on 2023-01-11 11:58

from django.db import migrations
from django.utils import timezone


def _fill(apps, _):
    from Users.models import Subscription

    subs_model: Subscription = apps.get_model("Users", "Subscription")
    for u_ in subs_model.objects.filter(started_at__isnull=False):
        u_.due_date = u_.started_at + timezone.timedelta(days=u_.duration)
        u_.save()


def _fill_rev(apps, _):
    subs_model = apps.get_model("Users", "Subscription")
    subs_model.objects.update(due_date=None)


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0013_remove_subscription_usage_at_expire_and_more"),
    ]

    operations = [migrations.RunPython(_fill, _fill_rev)]
