# Generated by Django 4.1.5 on 2023-01-12 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0015_alter_subscription_downlink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
