# Generated by Django 4.1.5 on 2023-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0016_subscription_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="uuid",
        ),
        migrations.AddField(
            model_name="subscription",
            name="task_expire_at_due_date_uid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
