# Generated by Django 4.1.5 on 2023-01-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0017_remove_subscription_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="due_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
