# Generated by Django 4.1.5 on 2023-01-18 16:03

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0018_alter_subscription_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="state",
            field=django_fsm.FSMField(
                choices=[("0", "Reserve"), ("1", "Active"), ("2", "Expire")],
                default="0",
                max_length=1,
                protected=True,
            ),
        ),
    ]
